esphome:
  name: lights

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:
  level: DEBUG
  hardware_uart: USB_SERIAL_JTAG

api:
  encryption:
    key: !secret esphome_lights_key

ota:
  platform: esphome
  password: !secret esphome_lights_password

ethernet:
  type: W5500
  clk_pin: GPIO13
  mosi_pin: GPIO11
  miso_pin: GPIO12
  cs_pin: GPIO14
  interrupt_pin: GPIO10
  reset_pin: GPIO9
  clock_speed: 25MHz
  manual_ip:
    static_ip: 10.0.1.4
    gateway: 10.0.1.1
    subnet: 255.255.255.0

web_server:
  local: true
  ota: false

light:
  - platform: monochromatic
    output: lights1
    name: Ceiling Lights 1
    icon: mdi:light-recessed
    restore_mode: RESTORE_DEFAULT_ON

  - platform: monochromatic
    output: lights2
    name: Ceiling Lights 2
    icon: mdi:light-recessed
    restore_mode: RESTORE_DEFAULT_ON

  - platform: monochromatic
    output: lights3
    name: Ceiling Lights 3
    icon: mdi:light-recessed
    restore_mode: RESTORE_DEFAULT_ON

  - platform: monochromatic
    output: lights4
    name: Ceiling Lights 4
    icon: mdi:light-recessed
    restore_mode: RESTORE_DEFAULT_ON

output:
  - platform: ledc
    id: lights1
    pin: GPIO1

  - platform: ledc
    id: lights2
    pin: GPIO2

  - platform: ledc
    id: lights3
    pin: GPIO15

  - platform: ledc
    id: lights4
    pin: GPIO18
